web:
    image: nginx:latest
    ports:
        - "8888:80"
    volumes:
        - ./src:/src
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./src:/src